#!/usr/bin/env python3
"""Emit the per-language glossary checklist for the audit sub-agent.

The audit sub-agent reads `loc_audit_prompt.md` verbatim with **no doc access**
(§ Sub-agent prompt). The prompt carries the terminology *rule* (how to flag);
this script carries the terminology *data* — the canonical per-language renderings
from `glossary.ndjson` — so the two never drift: the rule is authored once in the
prompt, the renderings are generated from the single glossary source of truth
(`GLOSSARY.md`, the glossary [CR-CORPUS-OWNER]).

    python3 loc_audit_glossary.py ru                       # → stdout
    python3 loc_audit_glossary.py ar /tmp/loc_gloss_ar.txt # → file

Inline the output above the `## Sub-agent prompt (calibrated)` block, alongside
the per-language calibration profile, exactly as `loc_audit_prompt.md § Workflow`
step 2 describes (header lines → calibration profile → glossary checklist →
prompt). Read-only (never writes the glossary); token-free.

Grouping (scan order for the agent):
  BRAND — do not translate          translatable:false (verbatim every language)
  BRAND — localized but consistent  tag `brand`, translatable
  FORBIDDEN — banned jargon         forbidden:true (flag if it appears in target)
  CANONICAL rendering               the rest, by primary tag (legal/unit/domain/ui/beverage)
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from loc_glossary import (  # noqa: E402
    DEFAULT_GLOSSARY,
    is_case_sensitive,
    is_forbidden,
    is_translatable,
    note,
    project_languages,
    read_records,
    tags,
    term,
    translation,
)
from loc_glossary import description as gloss_description  # noqa: E402

# Primary-tag priority for the CANONICAL group (a term lists once, under the
# first tag it carries in this order).
PRIMARY_TAG_ORDER = ("legal", "unit", "domain", "ui", "beverage")

HEADER = """\
# Glossary — canonical {lang} terminology (binding consistency checklist)
# Generated by loc_audit_glossary.py from glossary.ndjson — do NOT hand-edit.
#
# How to use (operationalizes audit rule #2 + TRANSLATION_STYLE.md § Lexicon):
#   When a key's `en` contains a term below, the {lang} target must render it as
#   shown. This is the agreed rendering across all 1200+ keys — a divergent target
#   is a consistency defect, not a free stylistic choice.
#     • FREEZE     — keep the term VERBATIM in {lang}; a translated / transliterated
#                    rendering is a defect → `lexicon` (or `brand-voice`) `error`.
#     • FORBIDDEN  — banned jargon; if it (or its {lang} calque shown) appears in the
#                    target on a casual/non-clinical surface, flag → `lexicon`/`calque`.
#                    Cross-language: a clinical EQUIVALENT is banned даже если технически
#                    верно (TRANSLATION_STYLE.md § Translation discipline Принцип #3).
#     • CANONICAL  — the agreed {lang} rendering; a divergent target → `lexicon` `warn`,
#                    but ONLY after the surface + note cross-check below.
#   Guardrails (avoid false positives):
#     • Cross-check the key's Surface/Register and the term's note before flagging —
#       some terms are surface-conditional (e.g. `hydration`, `water balance`) or have
#       no fixed form ("contextual" below); do NOT hard-flag those.
#     • The glossary `t` is the CONSISTENCY anchor, not an independent proof of
#       correctness. If you believe a listed rendering is itself wrong, say so in the
#       rationale — do not silently endorse the target's divergence from it.
#     • This does not override the existing skip rules (§ What NOT to flag) or the
#       ru cross-check (skip #16); it adds a terminology lane on top of them.
"""


def _fmt_note(text: str) -> str:
    """One-line the (possibly multi-line) glossary description for the checklist."""
    return " ".join(text.split()) if text else ""


def _value(record: dict, lang: str) -> str:
    rendered = translation(record, lang)
    if rendered:
        return f'"{rendered}"'
    if not is_translatable(record):
        return f'"{term(record)}" (verbatim)'
    return "(no fixed form — localize per note)"


def _line(record: dict, lang: str) -> str:
    flags = []
    if is_forbidden(record):
        flags.append("FORBIDDEN")
    if not is_translatable(record):
        flags.append("FREEZE")
    if is_case_sensitive(record):
        flags.append("CS")
    tag = "/".join(tags(record))
    flag_str = f" [{' '.join(flags)}]" if flags else ""
    tag_str = f" ({tag})" if tag else ""
    head = f"- {term(record)}{flag_str}{tag_str} : {_value(record, lang)}"
    lang_note = note(record, lang)
    desc = _fmt_note(gloss_description(record))
    tail = desc
    if lang_note:
        tail = f"{desc}  [{lang} note: {_fmt_note(lang_note)}]" if desc else f"[{lang} note: {_fmt_note(lang_note)}]"
    return f"{head}\n    {tail}" if tail else head


def _primary_tag(record: dict) -> str:
    record_tags = tags(record)
    for candidate in PRIMARY_TAG_ORDER:
        if candidate in record_tags:
            return candidate
    return "other"


def build(records: list[dict], lang: str) -> str:
    freeze, forbidden, brand_local, rest = [], [], [], []
    for record in records:
        if is_forbidden(record):
            forbidden.append(record)
        elif not is_translatable(record):
            freeze.append(record)
        elif "brand" in tags(record):
            brand_local.append(record)
        else:
            rest.append(record)

    out: list[str] = [HEADER.format(lang=lang)]

    def section(title: str, group: list[dict]) -> None:
        if not group:
            return
        out.append(f"\n## {title}")
        for record in sorted(group, key=term):
            out.append(_line(record, lang))

    section("BRAND — do not translate (verbatim in every language)", freeze)
    section("BRAND — localized but kept consistent", brand_local)
    section("FORBIDDEN — banned jargon (flag if it appears in the target)", forbidden)

    by_tag: dict[str, list[dict]] = {}
    for record in rest:
        by_tag.setdefault(_primary_tag(record), []).append(record)
    for tag in (*PRIMARY_TAG_ORDER, "other"):
        group = by_tag.get(tag)
        if group:
            section(f"CANONICAL rendering — {tag}", group)

    counts = (
        f"\n# totals: {len(records)} terms "
        f"(freeze={len(freeze)}, forbidden={len(forbidden)}, "
        f"brand-localized={len(brand_local)}, canonical={len(rest)})"
    )
    out.append(counts)
    return "\n".join(out) + "\n"


def usage() -> None:
    print("usage:", file=sys.stderr)
    print("  loc_audit_glossary.py <lang> [output_path]", file=sys.stderr)
    print("  emits the canonical per-language glossary checklist for the audit sub-agent", file=sys.stderr)
    print("  example: loc_audit_glossary.py ar /tmp/loc_gloss_ar.txt", file=sys.stderr)


def main() -> int:
    argv = sys.argv[1:]
    if not argv or argv[0] in {"-h", "--help"}:
        usage()
        return 2
    lang = argv[0]
    known = set(project_languages())
    if lang not in known:
        print(f"error: unknown language {lang!r}; known: {', '.join(sorted(known))}", file=sys.stderr)
        return 2
    if lang == "en":
        print("error: en is the headword/source column of the glossary — no per-language checklist", file=sys.stderr)
        return 2

    records = read_records(DEFAULT_GLOSSARY)
    rendered = build(records, lang)

    if len(argv) >= 2:
        out_path = Path(argv[1])
        out_path.write_text(rendered, encoding="utf-8")
        filled = sum(1 for r in records if translation(r, lang))
        print(f"wrote {out_path}: {len(records)} terms ({filled} with a {lang} rendering)")
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
